<?php

/**
 * @file
 * Core event dispatcher submodule.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\core_event_dispatcher\Event\Form\FormAlterEvent;
use Drupal\core_event_dispatcher\Event\Form\FormBaseAlterEvent;
use Drupal\core_event_dispatcher\Event\Form\FormIdAlterEvent;

// Form.
// @todo hook_ajax_render_alter()
// @todo hook_batch_alter()

/**
 * Implements hook_form_alter().
 *
 * {@inheritdoc}
 */
function core_event_dispatcher_form_alter(array &$form, FormStateInterface $formState, string $formId) {
  /* @var \Drupal\hook_event_dispatcher\Manager\HookEventDispatcherManagerInterface $manager */
  $manager = Drupal::service('hook_event_dispatcher.manager');
  $manager->register(new FormAlterEvent($form, $formState, $formId));

  $buildInfo = $formState->getBuildInfo();
  if (!empty($buildInfo['base_form_id'])) {
    /* @var \Drupal\core_event_dispatcher\Event\Form\FormBaseAlterEvent $event */
    $manager->register(new FormBaseAlterEvent($form, $formState, $formId, $buildInfo['base_form_id']));
  }
  $manager->register(new FormIdAlterEvent($form, $formState, $formId));
}
